import Interviews from "@/src/models/Interviews";
import { GetLatestInterviewsParams} from "@/src/types";
import { Interview } from "@/src/models/Interviews";

//function for getting the generated interviews from db in descending order
export  async function getInterviewByUserId(userId:string):Promise<Interview[] | null>{


    const interviews = await Interviews.find({userId}).sort({createdAt:-1});

    return interviews;
}

//function for getting the interviews generated by other users

export async function getLatestInterviews(params : GetLatestInterviewsParams):Promise<Interview[] | null>{

    const{userId , limit=20}=params;
    const interviews=await Interviews.find({
        finalized:true ,
        userId: {$ne : userId}

    }).sort({createdAt:-1})
    .limit(limit);
    return interviews;
}