import { GetLatestInterviewsParams} from "@/src/types";
import { Interview } from "@/src/types";
import Interviews from "../models/Interviews";
import dbConnect from "./dbConnect";
import { ObjectId } from "mongoose";




//function for getting the generated interviews from db in descending order
export  async function getInterviewByUserId(userId:string):Promise<Interview[] | null>{
    await dbConnect();

    const interviews = await Interviews.find({userId}).sort({createdAt:-1});

    return interviews;
}




//function for getting the interviews generated by other users
export async function getLatestInterviews(params : GetLatestInterviewsParams):Promise<Interview[] | null>{
     await dbConnect();
    const{userId , limit=20}=params;
    const interviews=await Interviews.find({
        finalized:true ,
        userId: {$ne : userId}

    }).sort({createdAt:-1})
    .limit(limit);
    return interviews;
}


//here we will get the interview by interview id
export async function getInterviewById(id:string): Promise<Interview>{
await dbConnect();
 const interview = await Interviews.findById(id);
 return interview;
}